title: Program in Java
description: Write a function `add(int a, int b)` that returns the sum of `a` and `b`
hidden:
  - src/test/**
  - .codeclimate.yml
protected:
  - build.gradle
evaluation:
  - step: codeclimate
#  - step: junit
#    cmd: gradle test
